-- Pakistan Student Hub - PostgreSQL Seed Script
-- Only verified factual public data from official institutions

INSERT INTO universities (id, name, slug, short_name, logo, cover_image, description, city, province, campus_locations, university_type, sector, website, contact_email, phone, address, established_year, recognition_status, programs, faculties, admission_information, fee_information, hostel_information, scholarships, source_url, source_name, last_verified_at, verification_status)
VALUES
(
  'e62b1049-74e2-45e0-9426-5b9679c6d321',
  'National University of Sciences and Technology',
  'nust',
  'NUST',
  'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=160&auto=format&fit=crop&q=80',
  '/src/assets/images/hero_pakistan_campus_quad_1790711289843.jpg',
  'Premier public research university in Pakistan, chartered by Federal Government in 1991. Ranked top 400 globally by QS World Rankings.',
  'Islamabad',
  'Islamabad Capital Territory',
  ARRAY['Sector H-12 Islamabad', 'Rawalpindi', 'Risalpur', 'Karachi'],
  'Engineering, Technology & Research',
  'Public',
  'https://nust.edu.pk',
  'admissions@nust.edu.pk',
  '+92-51-90856878',
  'Sector H-12, Islamabad, 44000, Pakistan',
  1991,
  'HEC Recognized (Highest Category W4) · PEC Accredited',
  ARRAY['BS Computer Science', 'BS Software Engineering', 'BS Artificial Intelligence', 'BE Electrical Engineering', 'BBA'],
  ARRAY['SEECS', 'SMME', 'NBS', 'SCME'],
  'Admissions are conducted primarily through the NUST Entry Test (NET) or ACT/SAT.',
  'Approx. PKR 165,000 – 195,000 per semester for engineering & computing.',
  'On-campus hostels available in H-12 with 24/7 security and dining.',
  'HEC Need-Based, NUST Internal Financial Aid, and PEEF grants.',
  'https://nust.edu.pk/admissions/',
  'Official NUST Admissions Office & HEC Portal',
  NOW(),
  'Verified'
),
(
  'b83a2157-19d8-4f81-80a2-4a0e19c3b842',
  'Quaid-i-Azam University',
  'qau',
  'QAU',
  'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=160&auto=format&fit=crop&q=80',
  '/src/assets/images/scholarship_study_desk_1790711306968.jpg',
  'Founded in 1967 as University of Islamabad, Quaid-i-Azam University is Pakistan’s top-ranked public federal university.',
  'Islamabad',
  'Islamabad Capital Territory',
  ARRAY['University Road, Islamabad'],
  'General & Postgraduate Research',
  'Public',
  'https://qau.edu.pk',
  'admissions@qau.edu.pk',
  '+92-51-9064000',
  'Quaid-i-Azam University, Islamabad, 45320, Pakistan',
  1967,
  'HEC Recognized #1 Overall Public University · Federal Charter',
  ARRAY['BS Physics', 'BS Computer Science', 'BS International Relations', 'BS Economics'],
  ARRAY['Faculty of Natural Sciences', 'Faculty of Biological Sciences', 'Faculty of Social Sciences'],
  'Admissions open twice a year (Fall & Spring). Merit based on board marks and USAT/Entry test.',
  'Subsidized regular seats approx. PKR 45,000 – 65,000 per semester.',
  'Hostels available across multiple campus halls.',
  'HEC Ehsaas, HEC Need-Based, and Bait-ul-Maal assistance.',
  'https://qau.edu.pk/admissions/',
  'Official QAU Portal & Federal Gazette',
  NOW(),
  'Verified'
),
(
  'c94b3268-20e9-4a92-91b3-5b1f20d4c953',
  'Lahore University of Management Sciences',
  'lums',
  'LUMS',
  'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=160&auto=format&fit=crop&q=80',
  '/src/assets/images/career_student_internship_1790711337608.jpg',
  'Internationally acclaimed private research university based in Lahore, founded in 1984. Renowned for rigorous business, computer science, and liberal arts programs.',
  'Lahore',
  'Punjab',
  ARRAY['DHA Phase 5, Lahore'],
  'General, Business & Science',
  'Private',
  'https://lums.edu.pk',
  'admissions@lums.edu.pk',
  '+92-42-35608000',
  'Sector U, DHA Phase 5, Lahore Cantt, 54792, Pakistan',
  1984,
  'HEC Recognized · AACSB Accredited',
  ARRAY['BS Computer Science', 'BS Electrical Engineering', 'BSc Accounting and Finance', 'BA-LL.B'],
  ARRAY['SBASSE', 'SDSB', 'MGSHSS', 'SAHSL'],
  'Intake in Fall via LCAT or SAT I score, matric/O-Level and FSc/A-Level grades.',
  'Approx. PKR 480,000 – 580,000 per semester. 1 in 3 students receives generous financial aid.',
  'Extensive on-campus residential facilities with sports complexes.',
  'National Outreach Programme (NOP) 100% funded scholarship and LUMS Financial Aid.',
  'https://admission.lums.edu.pk/',
  'Official LUMS Admissions Office',
  NOW(),
  'Verified'
);

INSERT INTO site_settings (id, website_name, description, contact_email, footer_text, announcement_bar)
VALUES (
  1,
  'Pakistan Student Hub',
  'Comprehensive student portal for Pakistan: verified university admissions, scholarships, entry test schedules, past papers, and educational deadlines.',
  'support@pakistanstudenthub.pk',
  'Pakistan Student Hub is an independent educational portal dedicated to delivering strictly verified academic opportunities, university directories, and official deadlines to Pakistani students nationwide.',
  '{"enabled": true, "text": "Fall 2026 / Spring 2027 Admissions & HEC Scholarships are now active. Check verified deadlines!"}'
) ON CONFLICT (id) DO NOTHING;
